### ISSUE TITLE
Feedback on the completed thesis draft

### ISSUE THREAD

**Issue by jjumadinova** [ReadyResearchers/cmpsc-600-fall-2022-and-spring-2023-senior-thesis-donizk#7]
Hi @donizk, below is the feedback on your thesis document.

Overall, great work with strong writing! Below are some of the things I identified to make your work even stronger. Please address these issues in advance of submitting the final version of your comp. Here is a reminder of the remaining deadlines in CMPSC 610:

- **Week Fifteen (April 24 - April 28) through Week Sixteen (May 1 - May 5):**  Final revisions to senior thesis document.
- **May 5 by 11:59 PM**: Submit the final version of senior thesis as a tagged release in the document's GitHub repository.

You also need to respond to the questions that appear in the feedback below, they are labeled as **[Q:]**. Please respond to the questions within 24 hours of this issue submission, then you can work on making changes to the document throughout the remaining time before the May 5th deadline. For each question please provide an explanation of how you plan to address that item or if you already addressed it in the document, please provide information with the section and page number where it has been addressed.

### Feedback and Questions

- Please make sure that your document meets all of the baseline requirements outlined in the syllabus. You should use the syllabus as a checklist  to confirm that you meet every baseline requirement. 

- In addition to finishing the final version of thesis document you also need to have a completed version of your computational
artifact that meets all of the baseline requirements outlined in the syllabus.

- **[Q:]** Are there relevant references to make your claims about data reliability and issues in equity stronger? Please include references for arguments made in the Ethical Implications section that begins on page 15. Issues in Equity subsection especially deserves a deeper and stronger discussion.

- **[Q:]** What does "statistical significance" mean? You need to explain what it is, how it is evaluated, what `p` value is, etc. in the document, perhaps on page 95.

- The first regression Figure (112) should be explained in detail. Walk the reader through the sections shown in the figure and explain what each section is. 

- **[Q:]** How does a static dashboard and a confusion matrix accuracy result in ethical concerns? It feels like there is a step missing in your discussion of Future Ethical Implications.

- Rewrite a few sentences on page 32 under "Data Description" to be more scientific and less personal.

- Reformat vertical spacing on pages 48-51, ensuring vertical space before subheadings like "Hispanic Recording" and try to ensure that the subheading shows on the same page as the visual.

- There are a few of typos that I saw (repeated "the", misspelled words, for example "seperated"). Please read your document carefully, run it through a spellchecker if possible, and improve its readability by fixing those errors.

**Comment by donizk** [comment]
[Q:] Are there relevant references to make your claims about data reliability and issues in equity stronger? Please include references for arguments made in the Ethical Implications section that begins on page 15. Issues in Equity subsection especially deserves a deeper and stronger discussion.

I did not reference any literature/other sources in the Ethical Implications. I can, however, find additional references to include to further bolster the claims made in this section. Beyond that, how should I consider deepening the discussion of Ethical Implications?

[Q:] What does "statistical significance" mean? You need to explain what it is, how it is evaluated, what p value is, etc. in the document, perhaps on page 95.

Statistical significance refers to the finding of significance in a variable used in the regression, determined by the interpretation of the p-values and confidence intervals, but also indicated by the asterisks next to these values on the regression summary output.

[Q:] How does a static dashboard and a confusion matrix accuracy result in ethical concerns? It feels like there is a step missing in your discussion of Future Ethical Implications.

I think that the nature of the static dashboard results in ethical concerns due to the inability to continuously add more data to it, making it confined to the data that the project was developed with. This may come as an issue, as the findings presented may not be as accurate, as the information presented may degrade with time. As for the confusion matrix, a potential ethical implication could be the fact that the confusion matrix was not implemented in the suggested manner, which could make the accuracy resulting from this unreliable -- meaning that the model generated may be more or less accurate than what is actually reported.

**Comment by donizk** [comment]
The following changes have been made to the document to adhere to the suggested revisions:
- reformat Data Description
- address problems with spelling and spacing
- added to Future Ethical Implications and Issues in Equity sections
- added a blurb about statistical significance and p-values.

**Comment by jjumadinova** [comment]
@donizk Your thesis release 3.0.1 satisfies the baseline requirements and incorporated all feedback provided to you after the defense. Congratulations, you have passed CMPSC 610 and are now officially de-comped!

Please upload your comprehensive thesis document to DSpace. Also, if you would like to have hard copies of your comp, please see Sabina Gora, our building coordinator, to get that process started.
